services:
  heartos-backend:
    build: .
    container_name: heartos-backend
    env_file:
      - .env
    ports:
      - "${APP_PORT:-9010}:${APP_PORT:-9010}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

