FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY .env.example ./.env.example

ENV APP_HOST=0.0.0.0
ENV APP_PORT=9000
EXPOSE 9000

CMD ["python", "-m", "app.main"]
