services:
  heartos-backend:
    build: .
    container_name: heartos-backend
    ports:
      - "9000:9000"
    environment:
      APP_NAME: HeartOS Backend
      APP_ENV: prod
      APP_HOST: 0.0.0.0
      APP_PORT: 9000
      APP_CORS_ORIGINS: "http://127.0.0.1:8080,http://localhost:8080"
      APP_HTTP_TIMEOUT: 45
      APP_HTTP_RETRIES: 2
      APP_MAX_UPLOAD_MB: 20
      APP_UPLOAD_DIR: /app/data/uploads
      APP_PUBLIC_BASE_URL: http://127.0.0.1:9000
      APP_ECGOMICS_URL: http://110.157.241.24:18023/ECGOmics
      APP_AI_ECG_DIGITIZE_URL: http://110.157.241.24:18022/digitize
      APP_ECG_RECONSTRUCT_URL: http://219.147.100.43:18007/reconstruct
    volumes:
      - ./data:/app/data
    restart: unless-stopped

